feat: game list component and scene
junpolo/user-management-system pull request #2
Opened 2024-02-23 06:02 UTC by TheAlfran

2024-02-23 06:06 UTC, CL3V submitted a review, later dismissed

2024-02-23 07:43 UTC, CL3V approved these changes, later dismissed

2024-02-23 07:47 UTC, junpolo commented on public/images/cover1.jpeg
optimize image kay dako ang file size

2024-02-23 08:21 UTC, junpolo requested changes
to reivew

2024-02-23 23:42 UTC, junpolo commented on src/@core/component/game-list.component.tsx
transfer file to `scenes/Dashboard/components`

2024-02-23 23:42 UTC, junpolo commented on src/scenes/shared/Gamelist/game-list-scene.tsx
transfer to `scenes/Dashboard/scenes`

2024-02-23 23:43 UTC, junpolo commented on src/scenes/shared/Gamelist/hooks/game-data.ts
Dili ni hook. Transfer to `@core/data` or `Dashboard/data`

2024-02-26 01:36 UTC, junpolo requested changes
Ayaw na isulod sa `GameList` na folder.

2024-02-26 01:43 UTC, junpolo commented on src/scenes/Dashboard/components/data/game-data.ts
dapat ang `data` folder is same level sa `components`

2024-02-26 01:44 UTC, junpolo commented on src/scenes/Dashboard/components/scene/game-list-scene.tsx
foldername should be plural

2024-02-26 01:44 UTC, junpolo requested changes
.

2024-02-26 01:55 UTC, junpolo approved these changes

2024-02-26 01:56 UTC, CL3V approved these changes

2024-02-26 01:57 UTC, merged